language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn testinci
  - yarn build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: now ./build --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now ./build --public --token $NOW_TOKEN && now alias --local-config=./build/now.json --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
